"""Pricing engine: pure Python, no dependency on the interface.

Gathers the engine's public names in one place, so callers can write
``from options_simulator.pricing import black_scholes``.

ARCHITECTURAL CONSTRAINT: this package imports nothing from the presentation
layer. It is testable in isolation, usable from a notebook and reusable by any
interface. A ``from ..app import ...`` in here would be a bug.
"""

from .binomial import binomial_price, binomial_price_and_greeks
from .black_scholes import black_scholes, black_scholes_price, probability_itm
from .greeks import (
    clear_price_cache,
    leg_greeks,
    position_greeks,
    price_and_greeks,
    price_cache_info,
    price_option,
)
from .implied import implied_volatility
from .merton import (
    NO_JUMPS,
    TYPICAL_CRASHES,
    FitQuote,
    JumpParams,
    MertonFit,
    calibrate_merton,
    merton_price,
    merton_price_and_greeks,
    merton_prices,
    merton_probability_below,
)
from .normal import norm_cdf, norm_pdf
from .payoff import (
    LegCost,
    MoneynessCode,
    PayoffBounds,
    TradeCost,
    break_evens,
    intrinsic_at_expiry,
    leg_entry_premium,
    moneyness,
    net_cost,
    payoff_bounds,
    pl_at_expiry,
    pl_at_market,
    probability_of_profit,
    resolve_legs,
    trade_cost,
)
from .types import (
    STEPS_BY_RESOLUTION,
    ExerciseStyle,
    Greeks,
    Leg,
    ManualPremium,
    MarketParams,
    OptionLeg,
    OptionSpec,
    PremiumSource,
    PricedOption,
    Resolution,
    ResolvedLeg,
    Right,
    Side,
    Sizing,
    StockLeg,
    TheoreticalPremium,
    effective_iv,
    spec_for_leg,
    years_from_days,
)

__all__ = [
    "NO_JUMPS",
    "STEPS_BY_RESOLUTION",
    "TYPICAL_CRASHES",
    "ExerciseStyle",
    "FitQuote",
    "Greeks",
    "JumpParams",
    "Leg",
    "LegCost",
    "ManualPremium",
    "MarketParams",
    "MertonFit",
    "MoneynessCode",
    "OptionLeg",
    "OptionSpec",
    "PayoffBounds",
    "PremiumSource",
    "PricedOption",
    "Resolution",
    "ResolvedLeg",
    "Right",
    "Side",
    "Sizing",
    "StockLeg",
    "TheoreticalPremium",
    "TradeCost",
    "binomial_price",
    "binomial_price_and_greeks",
    "black_scholes",
    "black_scholes_price",
    "break_evens",
    "calibrate_merton",
    "clear_price_cache",
    "effective_iv",
    "implied_volatility",
    "intrinsic_at_expiry",
    "leg_entry_premium",
    "leg_greeks",
    "merton_price",
    "merton_price_and_greeks",
    "merton_prices",
    "merton_probability_below",
    "moneyness",
    "net_cost",
    "norm_cdf",
    "norm_pdf",
    "payoff_bounds",
    "pl_at_expiry",
    "pl_at_market",
    "position_greeks",
    "price_and_greeks",
    "price_cache_info",
    "price_option",
    "probability_itm",
    "probability_of_profit",
    "resolve_legs",
    "spec_for_leg",
    "trade_cost",
    "years_from_days",
]
